### ISSUE TITLE
Application Service registration file options undocumented

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-doc#1259]
Application Service registration files support `rate_limited` and `protocols` fields, however we don't specify this anywhere in the [Application Service Documentation](https://matrix.org/docs/spec/application_service/unstable.html#registration).

Ideally we would have a table to break down and explain every possible AS registration file option and whether each is required or not.

**Comment by turt2live** [comment]
Also the `group_id` for the users regex

**Comment by anoadragon453** [comment]
Thanks, will note that one down too.

**Comment by turt2live** [comment]
to clarify, it's this:
```
namespaces:
  users:
    - exclusive: true
      regex: '@_discord_.*'
      group_id: '+discord:t2bot.io'
```
