### ISSUE TITLE
Contradictory documentation of keys in /search API

### ISSUE THREAD

**Issue by Sharparam** [matrix-org/matrix-doc#1972]
The documentation for `keys` for the type "Room Events Criteria" under [the `/search` API](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-search) says this:

> The keys to search. Defaults to all. One of: `["content.body", "content.name", "content.topic"]`

However, the type of the property is `[enum]` (array) and the example is also an array containing one of the enum values.

Is it true that only one of the enum values can be supplied? And if so, why is it an array?

**Comment by Half-Shot** [comment]
I think this is an example of it being badly explained in the docs rather than wrong. What the docs are trying to say is that the property is a array that can contain any of those 3 strings, rather than just one of them. 

It may have been better to say:

> The keys to search. Defaults to all. Any of: ["content.body", "content.name", "content.topic"]

**Comment by Sharparam** [comment]
Yeah, either "any" or "one or more".

**Comment by uhoreg** [comment]
It looks like this is all the fault of automatically-generated text.  The source file for the API just says:

```
                      keys:
                        type: array
                        items:
                          type: string
                          enum: ["content.body", "content.name", "content.topic"]
                        description: The keys to search. Defaults to all.
```

The document generator sees the enum, and inserts the "One of: ..." text.
