### ISSUE TITLE
Spec writing: put common values like senders, room IDs, aliases, etc in a shared location 

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-doc#2759]
At the moment each example is responsible for trying to be consistent with all its `$ref`s, which is a bit annoying. It'd be nice to be able to say `%(roomId)` or similar and have the spec generator automatically populate that field with a known value, allowing for consistency.

**Comment by KitsuneRal** [comment]
For YAML parts, anchors look like a natural answer that works right now. Just tried it on `banning.yaml`: assuming
```yaml
            example: {
                "reason": "Telling unfunny jokes",
                "user_id": &user_id1 "@cheeky_monkey:matrix.org"
              }
```
in `/ban` and
```yaml
            example: {
                "user_id": *user_id1
              }
```
in `/unban`, the rendered spec has the resolved anchor in both places. Using a non-existent anchor leads to a very readable "yaml.composer.ComposerError: found undefined alias 'no_such_anchor'" error message.
